server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/example
          jwk-set-uri: http://localhost:8081/realms/example/protocol/openid-connect/certs
          # http://localhost:8081/realms/example/.well-known/openid-configuration
          # http://localhost:8081/realms/example/.well-known/openid-configuration/issuer

          # http://localhost:8081/realms/example/.well-known/openid-configuration